import type { UsageActivityRow, UsageActivitySnapshot, UsageStatisticsGetInput, UsageStatisticsSnapshot } from "@actspace/shared";
import { aggregateActivities, summarizeActivityCosts } from "./usage-aggregates.js";

export type IndexedUsageSource = {
  readonly sessionId: string;
  readonly title: string | null;
  readonly throughJournalSeq: number;
  readonly rows: readonly UsageActivityRow[];
};

export function projectIndexedUsageActivity(sources: readonly IndexedUsageSource[], input: UsageStatisticsGetInput): UsageActivitySnapshot | null {
  const scope = input.scope ?? (input.sessionId ? "session" : "global");
  const selected = scope === "session" ? sources.filter(source => source.sessionId === input.sessionId) : sources;
  if (scope === "session" && selected.length === 0) return null;
  const rangeRows = selected.flatMap(source => source.rows).filter(row => inRange(row.startedAt, input.range ?? "month"));
  const groups = aggregateActivities(rangeRows);
  const rows = rangeRows.filter(row => (!input.kind || row.kind === input.kind) && (!input.search?.trim() || `${row.model ?? ""} ${row.providerId ?? ""} ${row.connectionId ?? ""} ${row.toolName ?? ""}`.toLowerCase().includes(input.search.trim().toLowerCase())) && (!input.status || input.status === "all" || row.status === input.status)).sort((a, b) => b.startedAt.localeCompare(a.startedAt) || b.sourceEventSeq - a.sourceEventSeq);
  const pageSize = 10; const totalPages = Math.max(1, Math.ceil(rows.length / pageSize)); const page = Math.min(Math.max(1, input.requestRowsPage?.page ?? 1), totalPages);
  const summary = rows.reduce((result, row) => { result.activityCount++; row.kind === "llm_request" ? result.requestCount++ : result.toolCount++; result[`${row.status}Count` as "successCount"]++; result.inputTokens += row.tokens.inputTokens ?? 0; result.outputTokens += row.tokens.outputTokens ?? 0; result.cacheReadTokens += row.tokens.cacheReadTokens ?? 0; result.cacheWriteTokens += row.tokens.cacheWriteTokens ?? 0; result.reasoningTokens += row.tokens.reasoningTokens ?? 0; result.totalTokens += row.tokens.totalTokens ?? 0; if (row.kind === "llm_request" && row.costAmount == null) result.costUnavailableCount++; if (row.costUsd !== null) result.costUsd = (result.costUsd ?? 0) + row.costUsd; return result; }, { activityCount: 0, requestCount: 0, toolCount: 0, successCount: 0, errorCount: 0, abortedCount: 0, runningCount: 0, unknownCount: 0, inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, reasoningTokens: 0, totalTokens: 0, costUsd: null as number | null, costUnavailableCount: 0 });
  return { schemaVersion: 1, scope, sessionId: scope === "session" ? input.sessionId ?? null : null, title: scope === "session" ? selected[0]?.title ?? "New chat" : "全部数据", range: input.range ?? "month", generatedAt: new Date().toISOString(), sourceCount: selected.length, sourceWatermarks: selected.map(source => ({ sessionId: source.sessionId, throughJournalSeq: source.throughJournalSeq })).sort((a, b) => a.sessionId.localeCompare(b.sessionId)), summary, tabCounts: { requests: rangeRows.length, providers: groups.providers.length, models: groups.models.length, tools: groups.tools.length }, costSummary: summarizeActivityCosts(rows), aggregates: aggregateActivities(rows), rows: rows.slice((page - 1) * pageSize, page * pageSize), rowsPage: { page, pageSize, totalRows: rows.length, totalPages } };
}

export function projectIndexedUsageStatistics(sources: readonly IndexedUsageSource[], input: UsageStatisticsGetInput): UsageStatisticsSnapshot | null {
  const activity = projectIndexedUsageActivity(sources, { ...input, kind: undefined, status: "all", search: undefined });
  if (!activity) return null;
  const rows = sources.filter(source => activity.scope === "global" || source.sessionId === activity.sessionId).flatMap(source => source.rows).filter(row => inRange(row.startedAt, activity.range));
  const requests = rows.filter(row => row.kind === "llm_request"); const tools = rows.filter(row => row.kind === "tool_invocation");
  const totalTokens = sum(requests, row => row.tokens.totalTokens); const promptTokens = sum(requests, row => row.tokens.inputTokens); const completionTokens = sum(requests, row => row.tokens.outputTokens); const cacheHitTokens = sum(requests, row => row.tokens.cacheReadTokens); const cacheMissTokens = sum(requests, row => row.tokens.cacheWriteTokens);
  const modelMap = group(requests, row => `${row.providerId ?? "default"}/${row.model ?? "default"}`); const toolMap = group(tools, row => row.toolName ?? "unknown"); const dayMap = group(rows, row => row.startedAt.slice(0, 10));
  const pageSize = 10; const totalPages = Math.max(1, Math.ceil(requests.length / pageSize)); const page = Math.min(Math.max(1, input.requestRowsPage?.page ?? 1), totalPages);
  return { scope: activity.scope, sessionId: activity.sessionId, title: activity.title, range: activity.range, generatedAt: activity.generatedAt, sourceCount: activity.sourceCount,
    summary: { totalTokens, promptTokens, completionTokens, cacheHitTokens, cacheMissTokens, reasoningTokens: sum(requests, row => row.tokens.reasoningTokens), toolCallCount: tools.length, conversationCount: new Set(requests.map(row => `${row.sessionId}:${row.agentRunId}`)).size, costUsd: sum(requests, row => row.costUsd), cacheEfficiencyPercent: totalTokens === 0 ? 0 : cacheHitTokens / totalTokens * 100 },
    modelDistribution: [...modelMap.entries()].map(([key, values]) => { const tokens = sum(values, row => row.tokens.totalTokens); const [provider, name] = key.split("/"); return { name: name ?? key, provider, totalTokens: tokens, percent: totalTokens === 0 ? 0 : tokens / totalTokens * 100, callCount: values.length, costUsd: sum(values, row => row.costUsd) }; }).sort((a, b) => b.totalTokens - a.totalTokens),
    toolDistribution: [...toolMap.entries()].map(([name, values]) => ({ name, callCount: values.length, percent: tools.length === 0 ? 0 : values.length / tools.length * 100, failedCount: values.filter(row => row.status === "error").length, averageDurationMs: values.length ? sum(values, row => row.durationMs) / values.length : undefined })).sort((a, b) => b.callCount - a.callCount),
    dailyRows: [...dayMap.entries()].map(([date, values]) => { const dailyRequests = values.filter(row => row.kind === "llm_request"); const dailyTotal = sum(dailyRequests, row => row.tokens.totalTokens); const models = group(dailyRequests, row => row.model ?? "default"); return { date, totalTokens: dailyTotal, promptTokens: sum(dailyRequests, row => row.tokens.inputTokens), completionTokens: sum(dailyRequests, row => row.tokens.outputTokens), cacheHitTokens: sum(dailyRequests, row => row.tokens.cacheReadTokens), reasoningTokens: sum(dailyRequests, row => row.tokens.reasoningTokens), conversationCount: new Set(values.map(row => `${row.sessionId}:${row.agentRunId}`)).size, toolCallCount: values.filter(row => row.kind === "tool_invocation").length, costUsd: sum(dailyRequests, row => row.costUsd), modelBreakdown: [...models.entries()].map(([name, modelRows]) => { const tokens = sum(modelRows, row => row.tokens.totalTokens); return { name, totalTokens: tokens, percent: dailyTotal === 0 ? 0 : tokens / dailyTotal * 100 }; }).sort((a, b) => b.totalTokens - a.totalTokens) }; }).sort((a, b) => a.date.localeCompare(b.date)),
    requestRows: requests.sort((a, b) => b.startedAt.localeCompare(a.startedAt)).slice((page - 1) * pageSize, page * pageSize).map(row => ({ timestamp: row.startedAt, sessionId: row.sessionId, agentRunId: row.agentRunId, ...(row.workspaceRoot ? { workspaceRoot: row.workspaceRoot } : {}), model: row.model ?? "default", ...(row.modelKey ? { modelKey: row.modelKey } : {}), ...(row.providerId ? { provider: row.providerId } : {}), modelCallCount: 1, totalTokens: row.tokens.totalTokens ?? 0, promptTokens: row.tokens.inputTokens ?? 0, completionTokens: row.tokens.outputTokens ?? 0, cacheHitTokens: row.tokens.cacheReadTokens ?? 0, cacheMissTokens: row.tokens.cacheWriteTokens ?? 0, reasoningTokens: row.tokens.reasoningTokens ?? 0, costUsd: row.costUsd ?? 0 })), requestRowsPage: { page, pageSize, totalRows: requests.length, totalPages } };
}

function inRange(value: string, range: NonNullable<UsageStatisticsGetInput["range"]>): boolean { if (range === "total") return true; const days = range === "day" ? 1 : range === "week" ? 7 : 31; return Date.parse(value) >= Date.now() - days * 86_400_000; }
function sum<T>(values: readonly T[], read: (value: T) => number | null | undefined): number { return values.reduce((total, value) => total + (read(value) ?? 0), 0); }
function group<T>(values: readonly T[], read: (value: T) => string): Map<string, T[]> { const result = new Map<string, T[]>(); for (const value of values) { const key = read(value); result.set(key, [...(result.get(key) ?? []), value]); } return result; }
