// Generated by scripts/check-browser-command-registry.mjs --write. Do not edit manually.

export const browserCommandRegistryVersion = "1";
export const browserCommandRegistryHash = "b73eb4308cf287f2651aebffb30f4db098529d90dd23b4364812c38af0b32dbb";

export const browserCommandMetadata = [
  {
    "id": "cua_get_visible_screenshot",
    "category": "cua",
    "action": "screenshot",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_cua",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_screenshot"
    ]
  },
  {
    "id": "cua_click",
    "category": "cua",
    "action": "click",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_cua",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "cua_double_click",
    "category": "cua",
    "action": "double_click",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_cua",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "cua_move",
    "category": "cua",
    "action": "move",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_cua",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "cua_scroll",
    "category": "cua",
    "action": "scroll",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_cua",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "cua_type",
    "category": "cua",
    "action": "type",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_cua",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "cua_keypress",
    "category": "cua",
    "action": "keypress",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_cua",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "cua_drag",
    "category": "cua",
    "action": "drag",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_cua",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "cua_download_media",
    "category": "cua",
    "action": "download_media",
    "riskLevel": "high",
    "readOnly": false,
    "effect": "download",
    "originPolicy": "target_origin",
    "previewKind": "browser_cua",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "dom_cua_get_visible_dom",
    "category": "dom",
    "action": "snapshot",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_dom",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "dom_cua_click",
    "category": "dom",
    "action": "click",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_dom",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "dom_cua_double_click",
    "category": "dom",
    "action": "double_click",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_dom",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "dom_cua_scroll",
    "category": "dom",
    "action": "scroll",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_dom",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "dom_cua_type",
    "category": "dom",
    "action": "type",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_dom",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "dom_cua_keypress",
    "category": "dom",
    "action": "keypress",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_dom",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "dom_cua_download_media",
    "category": "dom",
    "action": "download_media",
    "riskLevel": "high",
    "readOnly": false,
    "effect": "download",
    "originPolicy": "target_origin",
    "previewKind": "browser_dom",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_locator_click",
    "category": "locator",
    "action": "click",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_click"
    ]
  },
  {
    "id": "playwright_locator_dblclick",
    "category": "locator",
    "action": "double_click",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_locator_fill",
    "category": "locator",
    "action": "fill",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_fill"
    ]
  },
  {
    "id": "playwright_locator_press",
    "category": "locator",
    "action": "press",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_press_key"
    ]
  },
  {
    "id": "playwright_locator_select_option",
    "category": "locator",
    "action": "select_option",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_select"
    ]
  },
  {
    "id": "playwright_locator_set_checked",
    "category": "locator",
    "action": "set_checked",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_locator_inner_text",
    "category": "locator",
    "action": "inner_text",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_locator_text_content",
    "category": "locator",
    "action": "text_content",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_locator_all_text_contents",
    "category": "locator",
    "action": "all_text_contents",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_locator_read_all",
    "category": "locator",
    "action": "read_all",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_locator_get_attribute",
    "category": "locator",
    "action": "get_attribute",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_locator_is_visible",
    "category": "locator",
    "action": "is_visible",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_locator_is_enabled",
    "category": "locator",
    "action": "is_enabled",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_locator_count",
    "category": "locator",
    "action": "count",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_locator_wait_for",
    "category": "locator",
    "action": "wait_for",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_locator_download_media",
    "category": "locator",
    "action": "download_media",
    "riskLevel": "high",
    "readOnly": false,
    "effect": "download",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_dom_snapshot",
    "category": "locator",
    "action": "dom_snapshot",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_dom_snapshot"
    ]
  },
  {
    "id": "playwright_element_info",
    "category": "locator",
    "action": "element_info",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_element_screenshot",
    "category": "locator",
    "action": "element_screenshot",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_screenshot",
    "category": "locator",
    "action": "screenshot",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_scroll",
    "category": "locator",
    "action": "scroll",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_locator",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_scroll"
    ]
  },
  {
    "id": "navigate_tab_url",
    "category": "navigation",
    "action": "goto",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_navigation",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_navigate"
    ]
  },
  {
    "id": "navigate_tab_back",
    "category": "navigation",
    "action": "back",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_navigation",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_back"
    ]
  },
  {
    "id": "navigate_tab_forward",
    "category": "navigation",
    "action": "forward",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_navigation",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "navigate_tab_reload",
    "category": "navigation",
    "action": "reload",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_navigation",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "create_tab",
    "category": "tabs",
    "action": "create",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "requested_origin",
    "previewKind": "browser_tabs",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "tabs"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_open_tab"
    ]
  },
  {
    "id": "close_tab",
    "category": "tabs",
    "action": "close",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "target_origin",
    "previewKind": "browser_tabs",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "tabs"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_close_tab"
    ]
  },
  {
    "id": "list_tabs",
    "category": "tabs",
    "action": "list",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "session",
    "previewKind": "browser_tabs",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "tabs"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_list_tabs"
    ]
  },
  {
    "id": "selected_tab",
    "category": "tabs",
    "action": "selected",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "session",
    "previewKind": "browser_tabs",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "tabs"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "name_session",
    "category": "tabs",
    "action": "name_session",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "page_mutation",
    "originPolicy": "session",
    "previewKind": "browser_tabs",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "tab_groups"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "finalize_tabs",
    "category": "tabs",
    "action": "finalize",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "tab_cleanup",
    "originPolicy": "session",
    "previewKind": "browser_tabs",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "tabs",
      "tab_groups"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_finalize"
    ]
  },
  {
    "id": "browser_user_open_tabs",
    "category": "user",
    "action": "open_tabs",
    "riskLevel": "medium",
    "readOnly": true,
    "effect": "user_data_read",
    "originPolicy": "user_browser",
    "previewKind": "browser_user",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "tabs"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_user_tabs"
    ]
  },
  {
    "id": "browser_user_claim_tab",
    "category": "user",
    "action": "claim_tab",
    "riskLevel": "medium",
    "readOnly": false,
    "effect": "tab_claim",
    "originPolicy": "user_browser",
    "previewKind": "browser_user",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "tabs",
      "tab_groups"
    ],
    "status": "implemented",
    "legacyAliases": [
      "browser_claim_tab"
    ]
  },
  {
    "id": "browser_user_history",
    "category": "user",
    "action": "history",
    "riskLevel": "medium",
    "readOnly": true,
    "effect": "user_data_read",
    "originPolicy": "user_browser",
    "previewKind": "browser_user",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "history"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_wait_for_load_state",
    "category": "wait",
    "action": "load_state",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_wait",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_wait_for_url",
    "category": "wait",
    "action": "url",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "target_origin",
    "previewKind": "browser_wait",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_wait_for_timeout",
    "category": "wait",
    "action": "timeout",
    "riskLevel": "low",
    "readOnly": true,
    "effect": "read",
    "originPolicy": "session",
    "previewKind": "browser_wait",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "timer"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_wait_for_file_chooser",
    "category": "wait",
    "action": "file_chooser",
    "riskLevel": "medium",
    "readOnly": true,
    "effect": "file_chooser_observe",
    "originPolicy": "target_origin",
    "previewKind": "browser_wait",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "file_chooser_events"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_wait_for_download",
    "category": "wait",
    "action": "download",
    "riskLevel": "medium",
    "readOnly": true,
    "effect": "download_observe",
    "originPolicy": "target_origin",
    "previewKind": "browser_wait",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "downloads"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_file_chooser_set_files",
    "category": "io",
    "action": "set_file_chooser_files",
    "riskLevel": "high",
    "readOnly": false,
    "effect": "file_upload",
    "originPolicy": "target_origin",
    "previewKind": "browser_io",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "file_chooser"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "playwright_download_path",
    "category": "io",
    "action": "download_path",
    "riskLevel": "medium",
    "readOnly": true,
    "effect": "filesystem_metadata_read",
    "originPolicy": "target_origin",
    "previewKind": "browser_io",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "downloads"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "tab_clipboard_read_text",
    "category": "io",
    "action": "clipboard_read_text",
    "riskLevel": "medium",
    "readOnly": true,
    "effect": "clipboard_read",
    "originPolicy": "target_origin",
    "previewKind": "browser_io",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "clipboard"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "tab_clipboard_write_text",
    "category": "io",
    "action": "clipboard_write_text",
    "riskLevel": "high",
    "readOnly": false,
    "effect": "clipboard_write",
    "originPolicy": "target_origin",
    "previewKind": "browser_io",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "clipboard"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "tab_clipboard_read",
    "category": "io",
    "action": "clipboard_read",
    "riskLevel": "medium",
    "readOnly": true,
    "effect": "clipboard_read",
    "originPolicy": "target_origin",
    "previewKind": "browser_io",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "clipboard"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "tab_clipboard_write",
    "category": "io",
    "action": "clipboard_write",
    "riskLevel": "high",
    "readOnly": false,
    "effect": "clipboard_write",
    "originPolicy": "target_origin",
    "previewKind": "browser_io",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "clipboard"
    ],
    "status": "implemented",
    "legacyAliases": []
  },
  {
    "id": "tab_dev_logs",
    "category": "debug",
    "action": "logs",
    "riskLevel": "medium",
    "readOnly": true,
    "effect": "page_log_read",
    "originPolicy": "target_origin",
    "previewKind": "browser_debug",
    "backendRequirements": [
      "extension"
    ],
    "requiredCapabilities": [
      "cdp_events"
    ],
    "status": "implemented",
    "legacyAliases": []
  }
] as const;

export const browserActionsByCategory = {
  "cua": [
    "screenshot",
    "click",
    "double_click",
    "move",
    "scroll",
    "type",
    "keypress",
    "drag",
    "download_media"
  ],
  "dom": [
    "snapshot",
    "click",
    "double_click",
    "scroll",
    "type",
    "keypress",
    "download_media"
  ],
  "locator": [
    "click",
    "double_click",
    "fill",
    "press",
    "select_option",
    "set_checked",
    "inner_text",
    "text_content",
    "all_text_contents",
    "read_all",
    "get_attribute",
    "is_visible",
    "is_enabled",
    "count",
    "wait_for",
    "download_media",
    "dom_snapshot",
    "element_info",
    "element_screenshot",
    "screenshot",
    "scroll"
  ],
  "navigation": [
    "goto",
    "back",
    "forward",
    "reload"
  ],
  "tabs": [
    "create",
    "close",
    "list",
    "selected",
    "name_session",
    "finalize"
  ],
  "user": [
    "open_tabs",
    "claim_tab",
    "history"
  ],
  "wait": [
    "load_state",
    "url",
    "timeout",
    "file_chooser",
    "download"
  ],
  "io": [
    "set_file_chooser_files",
    "download_path",
    "clipboard_read_text",
    "clipboard_write_text",
    "clipboard_read",
    "clipboard_write"
  ],
  "debug": [
    "logs"
  ]
} as const;

export const browserLegacyAliases = {
  "browser_screenshot": {
    "category": "cua",
    "action": "screenshot",
    "commandId": "cua_get_visible_screenshot"
  },
  "browser_click": {
    "category": "locator",
    "action": "click",
    "commandId": "playwright_locator_click"
  },
  "browser_fill": {
    "category": "locator",
    "action": "fill",
    "commandId": "playwright_locator_fill"
  },
  "browser_press_key": {
    "category": "locator",
    "action": "press",
    "commandId": "playwright_locator_press"
  },
  "browser_select": {
    "category": "locator",
    "action": "select_option",
    "commandId": "playwright_locator_select_option"
  },
  "browser_dom_snapshot": {
    "category": "locator",
    "action": "dom_snapshot",
    "commandId": "playwright_dom_snapshot"
  },
  "browser_scroll": {
    "category": "locator",
    "action": "scroll",
    "commandId": "playwright_scroll"
  },
  "browser_navigate": {
    "category": "navigation",
    "action": "goto",
    "commandId": "navigate_tab_url"
  },
  "browser_back": {
    "category": "navigation",
    "action": "back",
    "commandId": "navigate_tab_back"
  },
  "browser_open_tab": {
    "category": "tabs",
    "action": "create",
    "commandId": "create_tab"
  },
  "browser_close_tab": {
    "category": "tabs",
    "action": "close",
    "commandId": "close_tab"
  },
  "browser_list_tabs": {
    "category": "tabs",
    "action": "list",
    "commandId": "list_tabs"
  },
  "browser_finalize": {
    "category": "tabs",
    "action": "finalize",
    "commandId": "finalize_tabs"
  },
  "browser_user_tabs": {
    "category": "user",
    "action": "open_tabs",
    "commandId": "browser_user_open_tabs"
  },
  "browser_claim_tab": {
    "category": "user",
    "action": "claim_tab",
    "commandId": "browser_user_claim_tab"
  }
} as const;

export type BrowserCommandMetadata = (typeof browserCommandMetadata)[number];
export type BrowserCategory = BrowserCommandMetadata["category"];
export type BrowserAction = BrowserCommandMetadata["action"];
